### ISSUE TITLE
Tuya Outlet Plug Powering off and On

### ISSUE THREAD

**Issue by apirotta** [fison67/TY-Connector#2]
I've installed the ty-connector docker container on a raspberry pi and have got it running in smartthings. It seems to be communicating with the device as the trigger from smartthings is briefly powering off the outlet however it instantly powers it back on automatically. I used smart life to connect the device and extract the localkey and deviceid and then uninstalled it from my phone.

Any suggestions?

**Comment by apirotta** [comment]
This is the output i get from the container. 

```2019-04-03 10:50:24 [info]: Tuya: Control >> {"id":"73484638cc50e3cc18a6","cmd":"power","data":"off","idx":"null"}
2019-04-03 10:50:29 [info]: Tuya: Device is disconnected
2019-04-03 10:50:30 [info]: Tuya: Device is connected
2019-04-03 10:50:35 [info]: Tuya: Device is disconnected
2019-04-03 10:50:36 [info]: Tuya: Device is connected
2019-04-03 10:50:36 [info]: Tuya:
2019-04-03 10:50:36 [info]: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at PlugDefault.notifyData (/usr/src/app/service/device/plug-default.js:13:28)
    at TuyaDevice.device.on.data (/usr/src/app/service/device/base.js:40:12)
    at TuyaDevice.emit (events.js:180:13)
    at Socket.client.on.data (/usr/src/app/node_modules/tuyapi/index.js:574:16)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onread (net.js:581:20)
2019-04-03 10:50:42 [info]: Tuya: Device is disconnected
2019-04-03 10:50:43 [info]: Tuya: Device is connected
2019-04-03 10:50:43 [info]: Tuya:
2019-04-03 10:50:43 [info]: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at PlugDefault.notifyData (/usr/src/app/service/device/plug-default.js:13:28)
    at TuyaDevice.device.on.data (/usr/src/app/service/device/base.js:40:12)
    at TuyaDevice.emit (events.js:180:13)
    at Socket.client.on.data (/usr/src/app/node_modules/tuyapi/index.js:574:16)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onread (net.js:581:20)
2019-04-03 10:50:49 [info]: Tuya: Device is disconnected
2019-04-03 10:50:50 [info]: Tuya: Device is connected
2019-04-03 10:50:50 [info]: Tuya:
2019-04-03 10:50:50 [info]: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at PlugDefault.notifyData (/usr/src/app/service/device/plug-default.js:13:28)
    at TuyaDevice.device.on.data (/usr/src/app/service/device/base.js:40:12)
    at TuyaDevice.emit (events.js:180:13)
    at Socket.client.on.data (/usr/src/app/node_modules/tuyapi/index.js:574:16)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onread (net.js:581:20)
2019-04-03 10:50:52 [info]: Tuya: {"1":true,"2":0}
2019-04-03 10:50:52 [info]: Tuya: {"2":0}
2019-04-03 10:50:57 [info]: Tuya: Device is disconnected
2019-04-03 10:50:57 [error]: (node:24) UnhandledPromiseRejectionWarning: Error: Timeout waiting for response
    at Timeout._sendTimeout.setTimeout [as _onTimeout] (/usr/src/app/node_modules/tuyapi/index.js:423:25)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
2019-04-03 10:50:57 [error]: (node:24) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 20)
2019-04-03 10:50:58 [info]: Tuya: Device is error >> Error: Error from socket
2019-04-03 10:50:58 [info]: Tuya: Device is disconnected
2019-04-03 10:50:59 [info]: Tuya: Device is connected
2019-04-03 10:50:59 [info]: Tuya:
2019-04-03 10:50:59 [info]: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at PlugDefault.notifyData (/usr/src/app/service/device/plug-default.js:13:28)
    at TuyaDevice.device.on.data (/usr/src/app/service/device/base.js:40:12)
    at TuyaDevice.emit (events.js:180:13)
    at Socket.client.on.data (/usr/src/app/node_modules/tuyapi/index.js:574:16)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onread (net.js:581:20)
2019-04-03 10:51:00 [info]: Tuya: {"1":true,"2":0}
2019-04-03 10:51:00 [info]: Tuya: {"2":0}
```

**Comment by fison67** [comment]
You mean that remove an smart life app?
Or remove device on smart life?

If you remove device, localkey is also expired.

**Comment by fison67** [comment]
And only one connection to one device is allowed.

**Comment by apirotta** [comment]
The smartlife is simply uninstalled, leaving the device active in the account. The device responds to my instruction and therefore i feel that configuration is somewhat correct

**Comment by apirotta** [comment]
Would you have any update please?

**Comment by fison67** [comment]
I don't know why it happens connect & disconnect...

**Comment by fison67** [comment]
If device's MCU firmware version is higher than 1.0.4, 
re-download a docker fison67/ty-connector:beta and recreate container.
Select a 3.3 version when you add a tuya device on ty connector web.
