### ISSUE TITLE
Log Error and Device Control Failure

### ISSUE THREAD

**Issue by jkessle2** [fison67/TY-Connector#5]
Hello.  I got the following log error from the TY-Connector portal Log:

Date	Type	Content
2019-06-21 10:59:16	error	Error: Not Found at /usr/src/app/app.js:137:13 at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5) at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13) at /usr/src/app/node_modules/express/lib/router/index.js:284:7 at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12) at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10) at /usr/src/app/node_modules/express/lib/router/index.js:635:15 at next (/usr/src/app/node_modules/express/lib/router/index.js:260:14) at Function.handle (/usr/src/app/node_modules/express/lib/router/index.js:174:3) at router (/usr/src/app/node_modules/express/lib/router/index.js:47:12)

I have no idea what this means.  The device registers to smartthings, but it does not respond to commands from the smartthings app even though I configured it as instructed.  What do I need to do?  Also, in smartthings IDE, the device says ACTIVE but does not say ONLINE.

Thanks.

**Comment by jkessle2** [comment]
This is a Tuya Color Bulb by the way.

**Comment by fison67** [comment]
What did you install a TY Connector docker version?
Install a fison67/ty-connector:beta version.

And then check your color bulb firmware version.
You can add device to ty connector on web page.
You have to select a version. 
If firmware is greater than 1.0.4 select a 3.3.

**Comment by jkessle2** [comment]
Where do I find the fison67/ty-connector:beta version?

**Comment by fison67** [comment]
It's a docker image.
