### ISSUE TITLE
Consistent error message even with beta 3.1 and 3.3

### ISSUE THREAD

**Issue by jkessle2** [fison67/TY-Connector#6]
I keep receiving this error message in the system log:

2019-07-13 09:01:27 | error | Error: Not Found at /usr/src/app/app.js:137:13 at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5) at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13) at /usr/src/app/node_modules/express/lib/router/index.js:284:7 at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12) at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10) at /usr/src/app/node_modules/express/lib/router/index.js:635:15 at next (/usr/src/app/node_modules/express/lib/router/index.js:260:14) at Function.handle (/usr/src/app/node_modules/express/lib/router/index.js:174:3) at router (/usr/src/app/node_modules/express/lib/router/index.js:47:12)
-- | -- | --

And device does not respond to controller inside SmartThings app although it does appear.

**Comment by fison67** [comment]
This is just other error log.
When wrong url is called.
