### ISSUE TITLE
Error: No connection has been made  to the device.

### ISSUE THREAD

**Issue by jezzaaa** [fison67/TY-Connector#8]
Hi

I'm trying to control a Tuya color bulb with ty-connector beta. Firmware is version 1.0.5 so created using v3.3. I copied IP, key and id from packet capture.

**Comment by jezzaaa** [comment]
Log shows connection problem:
```
2019-09-07 02:49:43 [TY-Connector] info: robe: Control >> {"id":"572757322cf432269a18","cmd":"power","data":"off","idx":"null"}
2019-09-07 02:49:43 [TY-Connector] error: (node:34) UnhandledPromiseRejectionWarning: Error: No connection has been made to the device.
    at TuyaDevice._send (/usr/src/app/node_modules/tuyapi/index.js:224:13)
    at Promise (/usr/src/app/node_modules/tuyapi/index.js:204:14)
    at new Promise (<anonymous>)
    at TuyaDevice.set (/usr/src/app/node_modules/tuyapi/index.js:201:12)
    at ColorLight.control (/usr/src/app/service/device/color-light.js:49:26)
    at TuyaService.control (/usr/src/app/service/tuya.js:74:14)
    at router.post (/usr/src/app/routes/index.js:58:21)
    at Layer.handle [as handle_request (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
2019-09-07 02:49:43 [TY-Connector] error: (node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 18)
2019-09-07 02:49:45 [TY-Connector] info: robe: Device is error >> Error: Error from socket
2019-09-07 02:49:45 [TY-Connector] info: robe: Device is disconnected
```

**Comment by jezzaaa** [comment]
At other times these errors keep showing:

```
2019-09-07 03:22:45 [TY-Connector] info: robe: Device is disconnected
2019-09-07 03:22:54 [TY-Connector] info: robe: Device is error >> Error: Error from socket
2019-09-07 03:22:54 [TY-Connector] info: robe: Device is disconnected
2019-09-07 03:22:59 [TY-Connector] info: robe: Device is connected
2019-09-07 03:22:59 [TY-Connector] info: robe: Device is error >> Error: Error from socket
2019-09-07 03:22:59 [TY-Connector] info: robe: Device is disconnected
```

**Comment by jezzaaa** [comment]
OK, so it wasn't obvious to me, but the IP address in the packet capture is the public NAT IP of my internet service. I had to reconfigure to the real IP address (192.168.1.100).

Now I'm getting "Device is connected" once, no more "Device is disconnected" and no more socket errors when I try to turn on or off.

However, it still isn't turning on or off. I get logs:
```
2019-09-07 09:29:54 [TY-Connector] info: robe: Control >> {"id":"572757322cf432269a18","cmd":"power","data":"on","idx":"null"}
2019-09-07 09:30:22 [TY-Connector] info: robe: Control >> {"id":"572757322cf432269a18","cmd":"power","data":"off","idx":"null"}
```
Is the "null" a problem, or do I need to set that to something?

**Comment by jezzaaa** [comment]
OK, so it wasn't obvious to me, but the IP address in the packet capture is the public NAT IP of my internet service. I had to reconfigure to the real IP address (192.168.1.100).

Now I'm getting "Device is connected" once, no more "Device is disconnected" and no more socket errors when I try to turn on or off.

However, it still isn't turning on or off. I get logs:
```
2019-09-07 09:29:54 [TY-Connector] info: robe: Control >> {"id":"572757322cf432269a18","cmd":"power","data":"on","idx":"null"}
2019-09-07 09:30:22 [TY-Connector] info: robe: Control >> {"id":"572757322cf432269a18","cmd":"power","data":"off","idx":"null"}
```
Is the "null" a problem, or do I need to set that to something?

**Comment by jezzaaa** [comment]
I'm making some progress, but still not working. Using "tuya-cli get" I can get the parameters. But only if I use just "--id" and not "--ip". If I use "--ip" it hangs forever. Could this be a problem with ty-connector also?

**Comment by fison67** [comment]
Did you set a local ip?

**Comment by jezzaaa** [comment]
> Did you set a local ip?

Yes I did. I also set a static DHCP IP so it won't change in the future.

A few more things I've discovered. The issue with tuya-cli hanging when specifying ip is because when called that way it defaults to v3.1 and my devices are v3.3. If I just use id, or if I specify v3.3 and ip, it works. That's all to say that tuya-cli allows me to turn the light on and off.

However, with tuya-cli I need to specify a dps index because the on/off flag is not at index 1, and instead is at index 20:

```
$ tuya-cli get --id 572757322cf432269a18 -a
{ devId: '572757322cf432269a18',
  dps:
   { '20': true,
     '21': 'white',
     '22': 150,
     '23': 44,
     '24': '00180389003c',
     '25': '04464602007803e803e800000000464602007803e8000a00000000' } }
```

I'm guessing that TY-Connector assumes the on/off DPS to be at index 1. I had a go at hacking the code in the container (running on a RPi) to allow me to specify a DPS offset (19 in my case) in the ty-config file, and have it add that to the DPS index when sending the message. But I'm not a JS coder so it didn't surprise me when it didn't work.

**Comment by jezzaaa** [comment]
OK, I'm getting closer now. With the DPS index offset, I was able to turn on the light. But SmartThings doesn't know that it was turned on. Instead it sits there saying "TURNING ON" and eventually says "OFF" (even though it's still on). I'm guessing SmartThings asks TY-Connector the status, and TY-Connector is reading with DPS index 1.

**Comment by fison67** [comment]
You can set a dps of power on setup.

**Comment by jezzaaa** [comment]
Ah, OK. Well, it would've saved me a bit of time, had I paid attention during setup!

What about the other parameters (mode, brightness, temperature, colour, scene)?

**Comment by jezzaaa** [comment]
Never mind, I found them. I don't see temperature, but I can live without that.

Thanks for all your help, and also for creating this and all of your other "*-Connector" utilities. They're extremely useful, and they look very professional.
